version: '2.1'
orbs:
  unity: game-ci/unity@1.4.0
workflows:
  build-unity-project:
    jobs:
      - checkout
      - unity/build:
          step-name: 'Build StandaloneWindows64'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-password-var-name: 'UNITY_PASSWORD'
          unity-username-var-name: 'UNITY_USERNAME'
          executor:
            name: 'unity/windows-2023'
            target_platform: 'windows-il2cpp'
            editor_version: '2023.2.0a19'
            name: 'unity/windows-2023'
            resource-class: 'large'
          name: build-Windows64-il2cpp
          project-path: BuisnessTycoon/
          build-target: StandaloneWindows64
          compress: true
          context: unity
